### ISSUE TITLE
GroovyCastException with closures/validation in command object

### ISSUE THREAD

**Issue by tjeerdnet** [rahulsom/swaggydoc#53]
I am using command objects in my controllers to hold the data coming in. The command objects looks like:

    class UserCommand implements grails.validation.Validateable {
    Integer id
    String username
    String password

    static constraints = {
        username(blank: false, minSize: 6)
        password(blank: false, minSize: 6)
    }
}

But this gives an error when I try to open the /api end point
`
Cannot cast object 'net.test.command.UserCommand$__clinit__closure1@433c198' with class 'net.test.command.UserCommand$__clinit__closure1' to class 'java.util.Map'. Stacktrace follows:
java.lang.reflect.InvocationTargetException: null
        at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.groovy:53) ~[spring-security-core-3.0.0.jar:na]
        at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.groovy:62) ~[spring-security-core-3.0.0.jar:na]
        at grails.plugin.springsecurity.web.SecurityRequestHolderFilter.doFilter(SecurityRequestHolderFilter.groovy:58) ~[spring-security-core-3.0.0.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_71]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_71]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_71]
Caused by: org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'net.test.command.UserCommand$__clinit__closure1@433c198' with class 'net.test.command.UserCommand$__clinit__closure1' to class 'java.util.Map'
        at com.github.rahulsom.swaggydoc.SwaggyDataService.getModels(SwaggyDataService.groovy:390) ~[swaggydoc-grails3-0.26.0.jar:na]
        at com.github.rahulsom.swaggydoc.SwaggyDataService.$tt__apiDetails(SwaggyDataService.groovy:151) ~[swaggydoc-grails3-0.26.0.jar:na]
        at grails.transaction.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:96) ~[grails-core-3.0.11.jar:3.0.11]
        at grails.transaction.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:93) ~[grails-core-3.0.11.jar:3.0.11]
        at com.github.rahulsom.swaggydoc.ApiController.show(ApiController.groovy:29) ~[swaggydoc-grails3-0.26.0.jar:na]
        ... 6 common frames omitted
`

Looks like it cannot cast the closure with the constraints to a map? Might this be because it expects a domain like class which differs from a command object?

**Comment by EpineiroBumeran** [comment]
Any help with this bug would be appreciated, specially because in Grails 2  command objects with constraints generate a correct swagger documentation with this plugin
