### ISSUE TITLE
Cannot cast object '[Digest Input Stream] MD5 Message Digest from SUN, <initialized>

### ISSUE THREAD

**Issue by hzhlu** [rahulsom/swaggydoc#57]
my project env: java1.8.0_72, groovy 2.4.7, grails 3.2.0, swaggydoc:0.28.0 
I buid a test project ,then copy from https://rahulsom.github.io/swaggydoc/guide/configuration.html  demo. my project start run ok, but swagger can't list controller api.    http://127.0.0.1:8080/api/index  
consol output error: 
ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[grailsDispatcherServlet] - Servlet.service() for servlet [grailsDispatcherServlet] in context with path [] threw exception
org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object '[Digest Input Stream] MD5 Message Digest from SUN, <initialized>
' with class 'java.security.DigestInputStream' to class 'java.io.ByteArrayInputStream'
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnSAM(DefaultTypeTransformation.java:405)
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnNumber(DefaultTypeTransformation.java:319)
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.castToType(DefaultTypeTransformation.java:232)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.castToType(ScriptBytecodeAdapter.java:603)
......

**Comment by smalints** [comment]
I have the same problem. @hzhlu may be you solved this problem?

**Comment by dodgerOn** [comment]
Try replacing `runtime "com.bertramlabs.plugins:asset-pipeline-grails:2.11.6"` with 
`runtime "org.grails.plugins:asset-pipeline"`
